set_property E15 [get_ports {sts_clk_pin_n}]
set_property IOSTANDARD LVDS_25 [get_ports {sts_clk_pin_n}]
set_property E14 [get_ports {sts_clk_pin_p}]
set_property IOSTANDARD LVDS_25 [get_ports {sts_clk_pin_p}]
set_property A17 [get_ports {sts_sin_pin_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {sts_sin_pin_n[0]}]
set_property A18 [get_ports {sts_sin_pin_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {sts_sin_pin_n[1]}]
set_property B12 [get_ports {sts_sin_pin_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {sts_sin_pin_n[2]}]
set_property J12 [get_ports {sts_sin_pin_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {sts_sin_pin_n[3]}]
set_property E13 [get_ports {sts_sin_pin_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {sts_sin_pin_n[4]}]
set_property A16 [get_ports {sts_sin_pin_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {sts_sin_pin_p[0]}]
set_property B18 [get_ports {sts_sin_pin_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {sts_sin_pin_p[1]}]
set_property C12 [get_ports {sts_sin_pin_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {sts_sin_pin_p[2]}]
set_property H11 [get_ports {sts_sin_pin_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {sts_sin_pin_p[3]}]
set_property F12 [get_ports {sts_sin_pin_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {sts_sin_pin_p[4]}]
set_property H17 [get_ports {sts_sout_pin_n}]
set_property IOSTANDARD LVDS_25 [get_ports {sts_sout_pin_n}]
set_property J17 [get_ports {sts_sout_pin_p}]
set_property IOSTANDARD LVDS_25 [get_ports {sts_sout_pin_p}]
