set eprj_proj_name "ripple_demo"
set eprj_def_root "."
set eprj_top_entity "ripple_counters"
set eprj_board_part ""
set eprj_part "xc7a100tfgg484-1"
set eprj_target_language "VHDL"
set eprj_simulator_language "Mixed"
set eprj_default_lib "work"
set eprj_synth_flow "Vivado Synthesis 2021"
set eprj_synth_strategy "Flow_AlternateRoutability"
set eprj_impl_flow "Vivado Implementation 2021"
set eprj_impl_strategy "Performance_ExplorePostRoutePhysOpt"
set eprj_vivado_version "2021.2"
set eprj_vivado_version_allow_upgrade true
