set eprj_proj_name "genlfsr"
set eprj_def_root "src"
set eprj_top_entity "genlfsr_top"
set eprj_board_files_path ""
set eprj_board_part ""
set eprj_part "xc7a200tfbg484-2"
set eprj_target_language "VHDL"
set eprj_simulator_language "Mixed"
set eprj_default_lib "work"
set eprj_synth_flow "Vivado Synthesis 2020"
set eprj_synth_strategy "Flow_PerfOptimized_high"
set eprj_impl_flow "Vivado Implementation 2020"
set eprj_impl_strategy "Performance_Retiming"
set eprj_vivado_version "2020.1"
set eprj_vivado_version_allow_upgrade true
